#ifndef TSIBU_I2C_CONSTANTS_HPP
#define TSIBU_I2C_CONSTANTS_HPP

#define I2C_WAIT_AFTER_FILE_OPEN_MICROSECONDS 2000000

#define I2C_PURGE_BUFFER_SIZE 512
#define I2C_READ_OPERATION_BUFFER_SIZE 8

#endif /* TSIBU_I2C_CONSTANTS_HPP */
