#ifndef TSIBU_SPI_CONSTANTS_HPP
#define TSIBU_SPI_CONSTANTS_HPP

#define SPI_CHANNEL_0 0
#define SPI_CHANNEL_1 1
#define SPI_DEFAULT_CHANNEL SPI_CHANNEL_0

#define SPI_DEFAULT_BUS_SPEED 500000

#define SPI_MESSAGE_BUFFER_SIZE 512

#endif /* TSIBU_SPI_CONSTANTS_HPP */
