#ifndef CURRENT_OPERATION_MODE_CONSTANTS_HPP
#define CURRENT_OPERATION_MODE_CONSTANTS_HPP

#include <string>

#define CURRENT_OPERATION_MODE_FSM_NAME std::string("operation_mode")

#define CURRENT_OPERATION_MODE_REEVALUATION_RATE_MILLISECONDS 1000 // 1 second

#endif /* CURRENT_OPERATION_MODE_CONSTANTS_HPP */
