#ifndef CURRENT_MOVEMENT_DIRECTION_CONSTANTS_HPP
#define CURRENT_MOVEMENT_DIRECTION_CONSTANTS_HPP

#include <string>

#define CURRENT_MOVEMENT_DIRECTION_FSM_NAME std::string("current_movement_direction")

#define CURRENT_MOVEMENT_DIRECTION_REEVALUATION_RATE_MILLISECONDS 200 // 1/5 of a second

#define CURRENT_MOVEMENT_DIRECTION_VARIABLE_LAST_STATE_CHANGE std::string("last_state_change")
#define CURRENT_MOVEMENT_DIRECTION_VARIABLE_STATE_STATIC_UNTIL std::string("state_static_until")

#endif /* CURRENT_MOVEMENT_DIRECTION_CONSTANTS_HPP */
