#ifndef CURRENT_MOVEMENT_DIRECTION_CONSTANTS_HPP
#define CURRENT_MOVEMENT_DIRECTION_CONSTANTS_HPP

#include <string>

#define CURRENT_MOVEMENT_DIRECTION_FSM_NAME std::string("current_movement_direction")

#define CURRENT_MOVEMENT_DIRECTION_REEVALUATION_RATE_MILLISECONDS 100 // 0.1 seconds

#define CURRENT_MOVEMENT_DIRECTION_VARIABLE_LAST_STATE_CHANGE std::string("last_state_change")
#define CURRENT_MOVEMENT_DIRECTION_VARIABLE_STATE_STATIC_UNTIL std::string("state_static_until")

#define CURRENT_MOVEMENT_DIRECTION_FORWARD_FACTOR 1.25

#endif /* CURRENT_MOVEMENT_DIRECTION_CONSTANTS_HPP */
